apiVersion: apps/v1
kind: Deployment
metadata:
  name: tt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tt
  template:
    metadata:
      labels:
        app: tt
    spec:
      containers:
      - image: okteto.dev/tt:latest
        name: tt
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: ProxySite
          value: "mirror.umd.edu"
        - name: Vless_UUID
          value: "ba336128-54d5-4805-9808-15a0d816a57c"
        - name: Vless_Path
          value: "/app"
        - name: Vmess_UUID
          value: "ba336128-54d5-4805-9808-15a0d816a57c"
        - name: Vmess_Path
          value: "/add"
        - name: Share_Path
          value: "$Share_Path"
